/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.ArrayList;
/**
 *
 * @author USER
 */
public class MatchSchedule extends javax.swing.JFrame {

    /**
     * Creates new form MatchSchedule
     */
    public MatchSchedule() {
        initComponents();
    }
    
    String emailaddress;
    String tourname;
    public MatchSchedule(String email, String tour) {
        initComponents();
        emailaddress = email;
        tourname = tour;
        userEmail.setText(emailaddress);
        tourName.setText(tourname);
        getteamCount();
        getteamNames();
        gettotalmatches();
    }
    
    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null;
    Statement St = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    int teamcount;
    int totalmatches;
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        exitBTN = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userEmail = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        backBTN = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        matchnumber = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        comboBox1 = new javax.swing.JComboBox<>();
        comboBox2 = new javax.swing.JComboBox<>();
        schedulenextMatch = new javax.swing.JLabel();
        nextBTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tourName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Java Projects\\CricScore Project\\Photos\\p1.png")); // NOI18N

        exitBTN.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        exitBTN.setForeground(new java.awt.Color(255, 255, 255));
        exitBTN.setText("X");
        exitBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBTNMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Match Schedule");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User :");

        userEmail.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        userEmail.setForeground(new java.awt.Color(255, 255, 255));
        userEmail.setText("user_email");

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));

        backBTN.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        backBTN.setForeground(new java.awt.Color(255, 255, 255));
        backBTN.setText("Back");
        backBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBTNMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        jLabel9.setText("Match ");

        matchnumber.setFont(new java.awt.Font("Engravers MT", 1, 18)); // NOI18N
        matchnumber.setText("1");

        jLabel11.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel11.setText("Team 1 ");

        jLabel12.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel12.setText("Team 2 ");

        comboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox1ActionPerformed(evt);
            }
        });

        schedulenextMatch.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        schedulenextMatch.setText("Next Match");
        schedulenextMatch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        schedulenextMatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schedulenextMatchMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(matchnumber))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(schedulenextMatch)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(matchnumber))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel12))
                .addGap(40, 40, 40)
                .addComponent(schedulenextMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        nextBTN.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        nextBTN.setText("NEXT");
        nextBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextBTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(395, Short.MAX_VALUE)
                .addComponent(backBTN)
                .addContainerGap(395, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(362, 362, 362))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(nextBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tournament Name :");

        tourName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        tourName.setForeground(new java.awt.Color(255, 255, 255));
        tourName.setText("tour_name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userEmail))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tourName))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(exitBTN)
                        .addGap(5, 5, 5))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(userEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tourName))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gettotalmatches(){
        totalmatches = 0;
        for (int i = 0; i < teamcount ; i++) {
            totalmatches += i;
        }
    }
    
    private void getteamCount(){
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT COUNT(*) as totalCount FROM teamnames WHERE TournamentName = '"+ tourname +"'");
            Rs.next();
            teamcount = Rs.getInt("totalCount");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e); 
        }
    }
    
    private void getteamNames(){
        try{
        ArrayList<String> list= new ArrayList<String>();
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","");
        St = Con.createStatement();
        Rs = St.executeQuery("SELECT TeamName FROM teamnames WHERE TournamentName = '"+ tourname +"'");
        while (Rs.next()) {
        list.add(Rs.getString(1));
        } 
            for (String i : list) {
                comboBox1.addItem(i);
                comboBox2.addItem(i);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e); 
        }
    }
    
    private void exitBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTNMouseClicked
        System.exit(1);
    }//GEN-LAST:event_exitBTNMouseClicked

    private void exitBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTNMouseEntered
        exitBTN.setBounds(800,0,30,30);
        exitBTN.setBackground(Color.red);
        exitBTN.setOpaque(true);
        this.setVisible(true);
    }//GEN-LAST:event_exitBTNMouseEntered

    private void exitBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTNMouseExited
        exitBTN.setBackground(new Color(0,0,153));
        this.setVisible(true);
    }//GEN-LAST:event_exitBTNMouseExited

    private void backBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBTNMouseClicked
        new RoundRobin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTNMouseClicked

    private void backBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBTNMouseEntered
        backBTN.setForeground(Color.RED);
    }//GEN-LAST:event_backBTNMouseEntered

    private void backBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBTNMouseExited
        backBTN.setForeground(Color.white);
    }//GEN-LAST:event_backBTNMouseExited

    private void comboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox1ActionPerformed
        
        String selectedValue = comboBox1.getSelectedItem().toString();
        //comboBox1 = settext(selectedValue);
    }//GEN-LAST:event_comboBox1ActionPerformed

    private void nextBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBTNMouseClicked
        new ScoreCard(emailaddress, tourname).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextBTNMouseClicked
   
    int rightrowcount = 1;
    private void tablerowCount(){
        int rowcount;
        String Query = "SELECT COUNT(*) AS rowcount FROM matchschedule";
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","");
            St = Con.createStatement();
            Rs = St.executeQuery(Query);
            Rs.next();
            rowcount = Rs.getInt("rowcount");
            rightrowcount = rowcount+1;
            //JOptionPane.showMessageDialog(this, rowcount); 
            Rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e); 
        }
        
//        Statement s = cd.createStatement();
//ResultSet r = s.executeQuery("SELECT COUNT(*) AS rowcount FROM TableName");
//r.next();
//int count = r.getInt("rowcount");
//r.close();
//System.out.println("MyTable has " + count + " row(s).");
    }
    
    boolean isAvailable;
    private boolean checkSimilarity(String t1, String t2){
        String Query = "Select * from matchschedule where Team1 = '"+ t1 +"' AND Team2 = '"+ t2 +"' OR Team1 = '"+ t2 +"' AND Team2 = '"+ t1 +"' ";
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","");
            St = Con.createStatement();
            Rs = St.executeQuery(Query);
            if (Rs.next()) {
                isAvailable = true;
            }else{
                isAvailable = false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e); 
        }return isAvailable;
    }
    
    private void schedulenextMatchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schedulenextMatchMouseClicked
        String team1= comboBox1.getSelectedItem().toString();
        String team2= comboBox2.getSelectedItem().toString();
        //checkSimilarity(team1, team2);       
        //rowcount = rowcount+1;
        if(checkSimilarity(team1, team2)){
            JOptionPane.showMessageDialog(this, "This match was previously added");
        }else if(team1.equals(team2)){
            JOptionPane.showMessageDialog(this, "Team 1 and Team 2 equal");
        }else{
            try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","");
            PreparedStatement Add = Con.prepareStatement("Insert into matchschedule values(?,?,?,?,?)");
            Add.setString(1, emailaddress);
            Add.setString(2, tourname); 
            Add.setInt(3, rightrowcount);
            Add.setString(4, team1);
            Add.setString(5, team2);
            int row = Add.executeUpdate();
            JOptionPane.showMessageDialog(this, "Schedule Created");
            Con.close();
            tablerowCount();
            matchnumber.setText(""+rightrowcount);
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            }
        }

    }//GEN-LAST:event_schedulenextMatchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatchSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatchSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatchSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatchSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatchSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBTN;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> comboBox1;
    private javax.swing.JComboBox<String> comboBox2;
    private javax.swing.JLabel exitBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel matchnumber;
    private javax.swing.JButton nextBTN;
    private javax.swing.JLabel schedulenextMatch;
    private javax.swing.JLabel tourName;
    private javax.swing.JLabel userEmail;
    // End of variables declaration//GEN-END:variables
}
