/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author USER
 */
public class RoundTeamNames extends javax.swing.JFrame {

    /**
     * Creates new form RoundTeamNames
     */
    public RoundTeamNames() {
        initComponents();
    }
    
    String emailaddress;
    String tourname;
    public RoundTeamNames(String email, String tour) {
        initComponents();
        emailaddress = email;
        tourname = tour;
        userEmail.setText(emailaddress);
        tourName.setText(tourname);
    }
    
    Connection Con = null;
    PreparedStatement pst = null;
    ResultSet Rs = null;
    Statement St = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        exitBTN = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userEmail = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        backBTN = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        teamname = new javax.swing.JTextField();
        teamnameaddBTN = new javax.swing.JButton();
        nextBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        numofplayers = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        playernumber = new javax.swing.JTextField();
        playername = new javax.swing.JTextField();
        playernameaddBTN = new javax.swing.JButton();
        playercount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        numofovers = new javax.swing.JTextField();
        ballsperover = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tourName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Java Projects\\CricScore Project\\Photos\\p1.png")); // NOI18N

        exitBTN.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        exitBTN.setForeground(new java.awt.Color(255, 255, 255));
        exitBTN.setText("X");
        exitBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitBTNMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Team Names");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("User :");

        userEmail.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        userEmail.setForeground(new java.awt.Color(255, 255, 255));
        userEmail.setText("user_email");

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));

        backBTN.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        backBTN.setForeground(new java.awt.Color(255, 255, 255));
        backBTN.setText("Back");
        backBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBTNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBTNMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Team Names");

        teamname.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        teamname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamnameActionPerformed(evt);
            }
        });

        teamnameaddBTN.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        teamnameaddBTN.setText("ADD");
        teamnameaddBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teamnameaddBTNMouseClicked(evt);
            }
        });
        teamnameaddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamnameaddBTNActionPerformed(evt);
            }
        });

        nextBTN.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        nextBTN.setText("NEXT");
        nextBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextBTNMouseClicked(evt);
            }
        });
        nextBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBTNActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Player ");

        numofplayers.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        numofplayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numofplayersActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. of Players Per Team");

        playernumber.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        playernumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playernumberActionPerformed(evt);
            }
        });

        playername.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        playername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playernameActionPerformed(evt);
            }
        });

        playernameaddBTN.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        playernameaddBTN.setText("ADD");
        playernameaddBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playernameaddBTNMouseClicked(evt);
            }
        });
        playernameaddBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playernameaddBTNActionPerformed(evt);
            }
        });

        playercount.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        playercount.setForeground(new java.awt.Color(255, 0, 0));
        playercount.setText("1");

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Num and Name");

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Balls Per Over");

        jLabel10.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("No. of Overs");

        numofovers.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        numofovers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numofoversActionPerformed(evt);
            }
        });

        ballsperover.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        ballsperover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ballsperoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(nextBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(385, 385, 385)
                                .addComponent(backBTN)))
                        .addGap(0, 183, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(teamnameaddBTN))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(playercount, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(playernumber, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(playername)
                                .addGap(18, 18, 18)
                                .addComponent(playernameaddBTN))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(numofplayers)
                                    .addComponent(teamname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numofovers, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ballsperover, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(91, 91, 91)))))
                .addGap(111, 111, 111))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teamname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numofplayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numofovers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ballsperover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(teamnameaddBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playercount, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playernumber, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playername, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playernameaddBTN))
                .addGap(20, 20, 20)
                .addComponent(nextBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tournament Name :");

        tourName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        tourName.setForeground(new java.awt.Color(255, 255, 255));
        tourName.setText("tour_name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userEmail))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tourName))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(exitBTN)
                        .addGap(5, 5, 5))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(exitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(userEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tourName))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTNMouseClicked
        System.exit(1);
    }//GEN-LAST:event_exitBTNMouseClicked

    private void exitBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTNMouseEntered
        exitBTN.setBounds(800,0,30,30);
        exitBTN.setBackground(Color.red);
        exitBTN.setOpaque(true);
        this.setVisible(true);
    }//GEN-LAST:event_exitBTNMouseEntered

    private void exitBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTNMouseExited
        exitBTN.setBackground(new Color(0,0,153));
        this.setVisible(true);
    }//GEN-LAST:event_exitBTNMouseExited

    private void backBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBTNMouseClicked
        new RoundRobin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBTNMouseClicked

    private void backBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBTNMouseEntered
        backBTN.setForeground(Color.RED);
    }//GEN-LAST:event_backBTNMouseEntered

    private void backBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBTNMouseExited
        backBTN.setForeground(Color.white);
    }//GEN-LAST:event_backBTNMouseExited

    private void teamnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamnameActionPerformed

    private void Clear(){
            teamname.setText("");   
    }
    
    private void teamnameaddBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teamnameaddBTNMouseClicked
        if (teamname.getText().isEmpty() || numofplayers.getText().isEmpty() || numofovers.getText().isEmpty() || ballsperover.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "Please Add Empty Values"); 
        }else{
            try {
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","");
                PreparedStatement Add = Con.prepareStatement("Insert into teamnames values(?,?,?,?,?,?)");
                Add.setString(1, emailaddress);
                Add.setString(2, tourname);
                Add.setString(3, teamname.getText());
                Add.setInt(4, Integer.valueOf(numofplayers.getText()));
                Add.setInt(5, Integer.valueOf(numofovers.getText()));
                Add.setInt(6, Integer.valueOf(ballsperover.getText()));
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Saved");
                Con.close();
                //Clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_teamnameaddBTNMouseClicked

    private void teamnameaddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamnameaddBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamnameaddBTNActionPerformed

    private void nextBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBTNMouseClicked
        new MatchSchedule(emailaddress, tourname).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nextBTNMouseClicked

    private void nextBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextBTNActionPerformed

    private void numofplayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numofplayersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numofplayersActionPerformed

    private void playernumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playernumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playernumberActionPerformed

    private void playernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playernameActionPerformed

    int rightrowcount = 1;
    private void tablerowCount(){
        int rowcount;
        String Query = "SELECT COUNT(*) AS rowcount FROM playername WHERE TeamName = '"+teamname.getText()+"'";
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","");
            St = Con.createStatement();
            Rs = St.executeQuery(Query);
            Rs.next();
            rowcount = Rs.getInt("rowcount");
            rightrowcount = rowcount+1;
            //JOptionPane.showMessageDialog(this, rowcount); 
            Rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e); 
        }
        
//        Statement s = cd.createStatement();
//ResultSet r = s.executeQuery("SELECT COUNT(*) AS rowcount FROM TableName");
//r.next();
//int count = r.getInt("rowcount");
//r.close();
//System.out.println("MyTable has " + count + " row(s).");
    }
    
    private void playernameaddBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playernameaddBTNMouseClicked
        if (playernumber.getText().isEmpty() || playername.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Add Player Name and Number"); 
        }else{
            try {
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/atmdb","root","");
                PreparedStatement Add = Con.prepareStatement("Insert into playername values(?,?,?,?,?,?)");
                Add.setString(1, emailaddress);
                Add.setString(2, tourname);
                Add.setString(3, teamname.getText());
                Add.setInt(4, Integer.valueOf(numofplayers.getText()));
                Add.setInt(5, Integer.valueOf(playernumber.getText()));
                Add.setString(6, playername.getText());
                int row = Add.executeUpdate();
                JOptionPane.showMessageDialog(this, "Player Name and Number Saved");
                Con.close();
                //Clear();
                tablerowCount();
                playercount.setText(""+rightrowcount);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_playernameaddBTNMouseClicked

    private void playernameaddBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playernameaddBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playernameaddBTNActionPerformed

    private void numofoversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numofoversActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numofoversActionPerformed

    private void ballsperoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ballsperoverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ballsperoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoundTeamNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoundTeamNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoundTeamNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoundTeamNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoundTeamNames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backBTN;
    private javax.swing.JTextField ballsperover;
    private javax.swing.JLabel exitBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton nextBTN;
    private javax.swing.JTextField numofovers;
    private javax.swing.JTextField numofplayers;
    private javax.swing.JLabel playercount;
    private javax.swing.JTextField playername;
    private javax.swing.JButton playernameaddBTN;
    private javax.swing.JTextField playernumber;
    private javax.swing.JTextField teamname;
    private javax.swing.JButton teamnameaddBTN;
    private javax.swing.JLabel tourName;
    private javax.swing.JLabel userEmail;
    // End of variables declaration//GEN-END:variables
}
